apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: updater
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: updater
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: updater
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      restartPolicy: Always
      volumes:
        - name: bottlerocket
          hostPath:
            path: /var/run/api.sock
      containers:
        - name: updater
          image: ghcr.io/pipetail/bottlerocket-updater/updater:linux-amd64-6d94851223843d858d3530efc21cce8308cf4b06
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          volumeMounts:
            - name: bottlerocket
              mountPath: /run/api.sock
          command:
            - /usr/local/bin/bottlerocket-updater
